[features]
seeds = true
skip-lint = false
[programs.localnet]
defios = "4UwHr76zjJaLxtbCmFmrWbkaZVVSujcumXjsFNhkBw3s"
[programs.devnet]
defios = "4UwHr76zjJaLxtbCmFmrWbkaZVVSujcumXjsFNhkBw3s"
[programs.testnet]
defios = "2oxTU2juQFMKqAhWNWFmU8Boxi39DwnEy8Nxt1xzHz5p"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"

[registry]
url = "https://damp-ancient-forest.solana-devnet.discover.quiknode.pro/4c38979f4ca8eca0840486c9d5f3f23a986c9cd2/"

[provider]
cluster = "devnet"
wallet = "/home/tanmay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
