[features]
seeds = false
skip-lint = false
[programs.localnet]
defios = "DppsrKuyLhDX7sZtn4KFoZuUrQPnfQcvqQWV1FTR15Hp"
token_vesting = "5kC3GR4DEgaF5e5UBH5VWsF1A5UVpLyHaqoWdFSCBMN7"
[programs.devnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"
[programs.testnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
