[features]
seeds = true
skip-lint = false
[programs.localnet]
defios = "BnWZUV3NTmXdADnWuzSR7urEdUyT9eLG74cpoCWKypyP"
skill_validator = "2HDrBtAm848yy8Swv92bzQdS8fmBjTbwJoN9vHLvvim7"
[programs.devnet]
defios = "BnWZUV3NTmXdADnWuzSR7urEdUyT9eLG74cpoCWKypyP"
skill_validator = "2HDrBtAm848yy8Swv92bzQdS8fmBjTbwJoN9vHLvvim7"

[registry]
url = "https://damp-ancient-forest.solana-devnet.discover.quiknode.pro/4c38979f4ca8eca0840486c9d5f3f23a986c9cd2/"

[provider]
cluster = "localnet"
wallet = "/home/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
