[features]
seeds = false
skip-lint = false
[programs.localnet]
defios = "7NWdxBpwFC5wyMiLb6viNyiZXyhmDhCM4zkdD8knPqJz"
[programs.devnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
[programs.testnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tanmay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
