[features]
seeds = false
skip-lint = false
[programs.localnet]
defios = "HdPtQX5VYkR5AbqgHTt5Rfaxhqgjryp73bmMrbFaLSo6"
token_vesting = "5Wm1LaCnGUY5S1om7qUy7PC6FnKRBCwxPLNeA97w17Hs"
[programs.devnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"
[programs.testnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tanmay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
