[features]
seeds = true
skip-lint = false
[programs.devnet]
defios = "vKAnobLTFv7uSdtjQWZohUSwW9NAH2XYfThYvkYhJz7"
skill_validator = "4BDizvrL519ChrLV8cpKhpCCPZUdpLcV9Q7mipKBHSLr"

[programs.localnet]
defios = "vKAnobLTFv7uSdtjQWZohUSwW9NAH2XYfThYvkYhJz7"
skill_validator = "4BDizvrL519ChrLV8cpKhpCCPZUdpLcV9Q7mipKBHSLr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/runner/.config/solana/id.json"
