[features]
seeds = true
skip-lint = false
[programs.localnet]
defios = "4k9tGk6zKfRoB2ajBuujNEduCciKrnSr93yaeCABUvTb"
skill_validator = "6kBEcnGqkC8aX7yEsTGZ2TVhFARsL8Yw2KaZkT8DzTcp"
[programs.devnet]
defios = "4k9tGk6zKfRoB2ajBuujNEduCciKrnSr93yaeCABUvTb"
skill_validator = "6kBEcnGqkC8aX7yEsTGZ2TVhFARsL8Yw2KaZkT8DzTcp"

[registry]
url = "https://damp-ancient-forest.solana-devnet.discover.quiknode.pro/4c38979f4ca8eca0840486c9d5f3f23a986c9cd2/"

[provider]
cluster = "localnet"
wallet = "/home/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
