[features]
seeds = false
skip-lint = false
[programs.localnet]
defios = "B7fYt6ZuT2Kw3tgtz3RXv6ADDQ3Tww9Zv4MLooRmd4fx"
token_vesting = "Uxg6s2212nfJrpogLQUvecey9kYUEWTaeBmUCsWBQWa"
[programs.devnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"
[programs.testnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
token_vesting = "vEsTJ2AkFvth5Cp8VvGAim1RFFTnyjPF3nxGZBm3Cbp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tanmay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
