[features]
seeds = true
skip-lint = false
[programs.localnet]
defios = "FNktGFqB6zpngB4HuJR4Q7VtThWVSBfvs4dGRZfZRAp1"
skill_validator = "J1YMNvSjANboNn6WNJUW5Wc7Jg5EuuHMQC1tZN5q1Rdo"
[programs.devnet]
defios = "FNktGFqB6zpngB4HuJR4Q7VtThWVSBfvs4dGRZfZRAp1"
skill_validator = "J1YMNvSjANboNn6WNJUW5Wc7Jg5EuuHMQC1tZN5q1Rdo"

[provider]
cluster = "localnet"
wallet = "/home/runner/.config/solana/id.json"

