[features]
seeds = true
skip-lint = false
[programs.localnet]
defios = "CAbANVD3AMTTmtadvkgKi4w2deSknK74eN7ej1Y3BskS"
[programs.devnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
[programs.testnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"

[registry]
url = "https://damp-ancient-forest.solana-devnet.discover.quiknode.pro/4c38979f4ca8eca0840486c9d5f3f23a986c9cd2/"

[provider]
cluster = "testnet"
wallet = "/home/tanmay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
