[features]
seeds = false
skip-lint = false
[programs.localnet]
defios = "7NWdxBpwFC5wyMiLb6viNyiZXyhmDhCM4zkdD8knPqJz"
[programs.devnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
[programs.testnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"
[programs.mainnet]
defios = "DEfiSZGJjNT5MShHgkFRCkiPEdRtzhcUdegzTP8t3SMR"

[registry]
url = "https://ancient-quick-frost.solana-testnet.discover.quiknode.pro/44bdd9af57d104e26d5bae07400c2fc8d8600507/"

[provider]
cluster = "https://ancient-quick-frost.solana-testnet.discover.quiknode.pro/44bdd9af57d104e26d5bae07400c2fc8d8600507/"
wallet = "/home/tanmay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/defios.ts"
