name: "Setup Python Program Compute check"
description: "Tests and outputs program compute on each instruction"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }} 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Decodes program compute logs
      run: python parse_program_compute.py
      shell: bash
