name: Tests

on:
  workflow_call:
    inputs:
      solana_cli_version:
        required: true
        type: string
      node_version:
        required: true
        type: string
      anchor_binary_name:
        required: true
        type: string
      anchor_version:
        required: true
        type: string
env:
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  ANCHOR_BINARY_NAME: ${{ inputs.anchor_binary_name }}
  ANCHOR_VERSION: ${{ inputs.anchor_version }}

jobs:
  test-core:
    name: Formatting tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: cargo fmt -- --check
      - run: npm i prettier
      - run: npm run lint 

  test-defios:
    name: Test DefiOS contracts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-amman/
      - run: cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --version ${{ env.ANCHOR_VERSION }} --locked --force
      - run: chmod +x ~/.cargo/bin/anchor
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ANCHOR_BINARY_NAME }}
          path: ~/.cargo/bin/anchor
      - run: anchor deploy --arch sbf -p defios
      - run: anchor deploy --arch sbf -p skill-validator
      - run: anchor keys sync
      - run: anchor test --arch sbf --skip-local-validator  --skip-deploy --run tests/DefiOS
      - uses: ./.github/actions/shutdown-validator/
      - uses: ./.github/actions/git-diff/

  test-skill-validator:
    name: Test SkillValidator contracts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-amman/
      - run: cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --version ${{ env.ANCHOR_VERSION }} --locked --force
      - run: chmod +x ~/.cargo/bin/anchor
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ANCHOR_BINARY_NAME }}
          path: ~/.cargo/bin/anchor
      - run: anchor deploy --arch sbf -p defios
      - run: anchor deploy --arch sbf -p skill-validator
      - run: anchor keys sync
      - run: anchor test --arch sbf --skip-local-validator --skip-deploy --run tests/SkillValidator
      - uses: ./.github/actions/shutdown-validator/
      - uses: ./.github/actions/git-diff/
