name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Reusable
    uses: ./.github/workflows/reusable_tests.yaml
    with:
      cache: true
      solana_cli_version: 1.14.20
      node_version: 17.0.1
      anchor_binary_name: anchor-binary